"""
Django settings for fzboard project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
import sys
import tempfile
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")

TESTING = "test" in sys.argv
TEST_RUNTIME_DIR = Path(tempfile.mkdtemp(prefix="fzboard-test-runtime-")) if TESTING else None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "fallback-insecure-key-do-not-use-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "t")

# Parse comma-separated list of allowed hosts
ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_vite",
    "dashboard",
]

# Custom user model
AUTH_USER_MODEL = 'dashboard.User'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fzboard.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "fzboard.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.getenv("DATABASE_PATH", BASE_DIR / "db.sqlite3"),
        "OPTIONS": {
            "timeout": 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [path for path in [BASE_DIR / "static"] if path.exists()]

DJANGO_VITE = {
    "default": {
        "dev_mode": os.environ.get("VITE_DEV_MODE", "0") == "1",
        "dev_server_port": 5173,
        "manifest_path": BASE_DIR / "static" / "dist" / ".vite" / "manifest.json",
        "static_url_prefix": "dist/",
    }
}

if TESTING:
    test_manifest_dir = TEST_RUNTIME_DIR / "static" / "dist" / ".vite"
    test_assets_dir = TEST_RUNTIME_DIR / "static" / "dist" / "assets"
    test_static_root = TEST_RUNTIME_DIR / "staticfiles"
    test_manifest_dir.mkdir(parents=True, exist_ok=True)
    test_assets_dir.mkdir(parents=True, exist_ok=True)
    test_static_root.mkdir(parents=True, exist_ok=True)

    manifest_path = test_manifest_dir / "manifest.json"
    manifest_path.write_text(json.dumps({
        "frontend/src/main.js": {
            "file": "assets/test-main.js",
            "name": "main",
            "src": "frontend/src/main.js",
            "isEntry": True,
            "css": ["assets/test-main.css"],
        }
    }))
    (test_assets_dir / "test-main.js").write_text("// test asset placeholder\n")
    (test_assets_dir / "test-main.css").write_text("/* test asset placeholder */\n")

    STATIC_ROOT = test_static_root
    DJANGO_VITE["default"]["dev_mode"] = False
    DJANGO_VITE["default"]["manifest_path"] = manifest_path


# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('MEDIA_ROOT_PATH', BASE_DIR / 'media')
if TESTING:
    MEDIA_ROOT = TEST_RUNTIME_DIR / "media"
    MEDIA_ROOT.mkdir(parents=True, exist_ok=True)

# Session expiration
SESSION_COOKIE_AGE = 3600
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
