# Generated by Django 6.0.1 on 2026-02-27 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='TemplateColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del encabezado de columna', max_length=255)),
                ('data_type', models.CharField(choices=[('text', 'Texto'), ('integer', 'Entero'), ('float', 'Decimal'), ('date', 'Fecha'), ('boolean', 'Booleano'), ('email', 'Correo Electrónico'), ('url', 'URL')], default='text', help_text='Tipo de dato de la columna', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de la columna en la tabla')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='dashboard.tabletemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
