# Generated by Django 6.0.1 on 2026-04-06 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dataset_datasetimport_datasetrow_datasetcellissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('layout_json', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dashboard.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('name', 'owner', 'dataset')},
            },
        ),
        migrations.CreateModel(
            name='ReportFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_kind', models.CharField(choices=[('template_column', 'Columna del Formato'), ('calculated_field', 'Campo Calculado')], default='template_column', max_length=20)),
                ('field_ref', models.PositiveIntegerField(help_text='ID de la columna o campo calculado')),
                ('operator', models.CharField(choices=[('equals', 'Igual a'), ('not_equals', 'Diferente de'), ('contains', 'Contiene'), ('not_contains', 'No contiene'), ('in_list', 'En lista'), ('gt', 'Mayor que'), ('gte', 'Mayor o igual que'), ('lt', 'Menor que'), ('lte', 'Menor o igual que'), ('between', 'Entre'), ('is_null', 'Es vacío'), ('is_not_null', 'No es vacío')], default='equals', max_length=20)),
                ('value_json', models.JSONField(blank=True, default=dict, help_text='{"value": ...} para escalar, {"values": [...]} para lista, {"min": ..., "max": ...} para rango')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='dashboard.report')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ReportWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('table', 'Tabla'), ('bar', 'Barras'), ('pie', 'Pastel'), ('scatter', 'Dispersión'), ('histogram', 'Histograma')], default='table', max_length=20)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('layout_x', models.PositiveIntegerField(default=0)),
                ('layout_y', models.PositiveIntegerField(default=0)),
                ('layout_w', models.PositiveIntegerField(default=12)),
                ('layout_h', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.report')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
