apiVersion: v2
name: fzboard
description: FzBoard - Django dashboard application with Svelte frontend
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - django
  - dashboard
  - svelte
maintainers:
  - name: mrfuzball
